// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",         Justification = "The file is autogenerated", Scope = "type", Target = "Arcade_r.InputSettingsActions")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "The file is autogenerated", Scope = "type", Target = "Arcade_r.InputSettingsActions")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces",            Justification = "The file is autogenerated", Scope = "type", Target = "Arcade_r.InputSettingsActions")]

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",         Justification = "The file is autogenerated", Scope = "type", Target = "SK.Libretro.Unity.Controls")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "The file is autogenerated", Scope = "type", Target = "SK.Libretro.Unity.Controls")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces",            Justification = "The file is autogenerated", Scope = "type", Target = "SK.Libretro.Unity.Controls")]

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",         Justification = "Same as the C header",      Scope = "type", Target = "SK.Libretro.Wrapper")]
